### ISSUE TITLE
L1->L2 gas feeds

### ISSUE THREAD

**Issue by augustbleeds** [ruleslabs/kass#1]
How do you plan on calculating L1->L2 gas feeds? Currently, https://github.com/ruleslabs/kass/blob/main/ethereum/src/Kass.sol#L193 is not sending any payment for the transaction to be executed on L2

**Comment by 0xChqrles** [comment]
Hi ! Fee mgmt will be implemented very soon, but the fee calculation will be done offchain

**Comment by augustbleeds** [comment]
Thanks for the answer! So by off-chain you mean that the external account would determine the fee calculation and pass that into the L1 contract function invocation as an argument?

Asking because I'm trying to figure out how to do fee calculation on-chain myself at the moment.

**Comment by 0xChqrles** [comment]
Starkgate already implemented L1 -> L2 fees mgmt. Basically you just have to pass the fee through `msg.value`, like [here](https://github.com/starknet-io/starkgate-contracts/blob/main/src/starkware/starknet/apps/starkgate/eth/StarknetEthBridge.sol#L14)

You can't access L2 contracts during L1 execution, so you can't calculate the fees onchain. To estimate the fees offchain you can use the [starknet CLI](https://docs.starknet.io/documentation/tools/CLI/commands/#starknet_estimate_message_fee) or [starknet.js](https://github.com/0xs34n/starknet.js/blob/develop/src/provider/sequencer.ts#L626). There's probably others libs to achieve this in other languages, or you can directly query the sequencer.

**Comment by 0xChqrles** [comment]
L1 -> L2 fee mgmt have been implemented with this [commit](https://github.com/ruleslabs/kass/commit/1e921855a03634ec27b55c2ecb599304a4f840b6)
